### ISSUE TITLE
Provide option to run on the given host

### ISSUE THREAD

**Issue by advoretsky** [nivertius/repositable#1]
It's unchangeable localhost now. Not appropriate for running inside docker container

**Comment by nivertius** [comment]
Added in 1.3.0.
If you actually build a dockercontainer, would you mind attaching dockerfile here or sending it to me?

**Comment by nivertius** [comment]
Or, you know, fork and send pull request. ;-)

**Comment by advoretsky** [comment]
To solve this issue without waiting I added nginx to the image, so my docker file is not relevant.
